[theme]
primaryColor = "#4A90E2"           # --primary-blue
backgroundColor = "#FFFFFF"        # --neutral-white
secondaryBackgroundColor = "#F5F5F5" # --neutral-light-gray
textColor = "#2C3E50"              # --neutral-dark
font = "Roboto"

# Optionally, adjust other theme settings as needed
